In [1]:
from sympy import Matrix
from sympy.physics.quantum import TensorProduct
import numpy as np


In [6]:
m1 = Matrix([[0,0],[0,1]])
m2 = Matrix([[1,0],[0,0]])

print(np.array(m1), "\n cuña \n", np.array(m2), " = \n") 
print(np.array(TensorProduct(m1, m2) - TensorProduct(m2, m1)))
print("\n")
print(np.array(m2), "\n cuña \n", np.array(m1), " = \n") 
print(np.array(TensorProduct(m2, m1) - TensorProduct(m1, m2)))


[[0 0]
 [0 1]] 
 cuña 
 [[1 0]
 [0 0]]  = 

[[0 0 0 0]
 [0 -1 0 0]
 [0 0 1 0]
 [0 0 0 0]]


[[1 0]
 [0 0]] 
 cuña 
 [[0 0]
 [0 1]]  = 

[[0 0 0 0]
 [0 1 0 0]
 [0 0 -1 0]
 [0 0 0 0]]


In [8]:
m1 = Matrix([[1], [0], [0], [0]])
m2 = Matrix([[0 ,1, 0, 0]])
m4 = Matrix([[0],[1], [0],[0]])
m3 = Matrix([[1, 0, 0, 0]])

print( np.array(m1), "\n tensor \n", np.array(m2))
print(" menos \n", np.array(m4), "\n tensor \n", np.array(m3), " = \n") 
print(np.array(TensorProduct(m1, m2) - TensorProduct(m4, m3)))


[[1]
 [0]
 [0]
 [0]] 
 tensor 
 [[0 1 0 0]]
 menos 
 [[0]
 [1]
 [0]
 [0]] 
 tensor 
 [[1 0 0 0]]  = 

[[0 1 0 0]
 [-1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
